export default async function handler(req, res) {
  const { partNumber } = req.body;
  
  if (!partNumber) {
    return res.status(200).json([]);
  }

  const prompt = `You are an expert electronics engineer and AI supply chain assistant.
The following critical component in our enterprise BOM has been disrupted: ${partNumber}

Using your deep knowledge of the semiconductor industry, identify 2 to 3 REAL, commercially available alternative components that are functionally equivalent, pin-compatible, or suitable drop-in replacements for ${partNumber}.

For each alternative, act as a global procurement engine and assign:
1. "partNumber": The real manufacturer part number of the alternative.
2. "vendor": A real, major electronics distributor that stocks it (e.g., "Digi-Key", "Mouser Electronics", "Arrow Electronics", "Avnet", "Future Electronics").
3. "note": A short engineering note (e.g., "Pin-to-pin compatible", "Requires minor PCB footprint change", "Different voltage rating").

Rank them from best (most compatible) to worst.
Return ONLY a valid JSON object containing an array called "matches", where each item has the exact keys: "partNumber", "vendor", and "note".

Example output format:
{
  "matches": [
    { "partNumber": "REAL_ALT_PART_NUM", "vendor": "Digi-Key", "note": "Pin-compatible replacement" }
  ]
}
`;

  try {
    const response = await fetch("https://api.groq.com/openai/v1/chat/completions", {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${process.env.GROQ_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: "openai/gpt-oss-120b",
        messages: [{ role: "user", content: prompt }],
        response_format: { type: "json_object" },
        temperature: 0.1
      }),
    });

    const data = await response.json();
    const content = data.choices[0].message.content;
    const parsed = JSON.parse(content);
    
    if (parsed.matches && Array.isArray(parsed.matches)) {
      res.status(200).json(parsed.matches);
    } else {
      throw new Error("Invalid format");
    }
  } catch (err) {
    console.error("Groq API Error in match:", err);
    res.status(200).json([
      { partNumber: "GENERIC-ALT-1", vendor: "Digi-Key", note: "Fallback alternative generated by system" }
    ]);
  }
}
